name: CI/CD Laravel Docker (Direct Build on Server)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Deploy via SSH to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: '36.94.79.204'
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "ðŸš€ Pulling latest changes..."
            git pull origin master --rebase
            /bin/bash /home/xlxtwc/Chronical_Project/twb-be/runner.sh
